/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.sink;

public class MyCustomSinkConverter {
    public boolean someLibraryMethod() {
        return true;
    }
}
