---
version: "2.1"
services:

  # Elasticsearch cluster. localhost 9200 (ensure this is open on host) --> container 9200
  # For simplicity, running only a single node here
  # To run multiple nodes on single machines: https://discuss.elastic.co/t/can-i-run-multiple-elasticsearch-nodes-on-the-same-machine/67
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    ### The env file can be used to define substitution-variables.
    ### This substitution variable of env is different from environment variable available inside container
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    environment:
      - cluster.name=es-cluster
      - node.name=es-node-1
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es-node-1
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      #      Set the file descriptors
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # ES data dir mount to local drive
      - ${ES_MOUNT_DRIVE}:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    # Internal network for the containers
    networks:
      - 'elk_stack'
    # Health check to confirm availability of ES. Other containers wait on this.
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:${ES_PASSWORD}", "http://localhost:9200/_cat/health"]

# network connectors used in the docker env
networks:
  elk_stack:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        # default docker compose subnet(172.177.0.0/16), which may overlap with existing services on home network.
#        # use this configuration to update to a different subnet
#        - subnet: 192.168.1.0/24